version: '3.8'

services:
  azure-storage-explorer:
    # For local development - build from source
    build:
      context: .
      dockerfile: Dockerfile
    # For production - use pre-built image from GHCR
    # image: ghcr.io/[username]/[repository]/azure-storage-explorer:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
      # Add your environment variables here
      # - AZURE_STORAGE_CONNECTION_STRING=${AZURE_STORAGE_CONNECTION_STRING}
      # - NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME=${NEXT_PUBLIC_AZURE_STORAGE_ACCOUNT_NAME}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    # Uncomment to add volume mounts for persistent data
    # volumes:
    #   - app-data:/app/data
    networks:
      - azure-storage-network

networks:
  azure-storage-network:
    driver: bridge

# Uncomment if you need persistent volumes
# volumes:
#   app-data: